export const pronounSet = [
  { char: "我", zhuyin: { symbol: "ㄨㄛˇ" } },
  { char: "你", zhuyin: { symbol: "ㄋㄧˇ" } },
  { char: "他", zhuyin: { symbol: "ㄊㄚ" } },
  { char: "她", zhuyin: { symbol: "ㄊㄚ" } },
  { char: "們", zhuyin: { symbol: "ㄇㄣ˙" } },
];

export const basicSet = [
  { char: "是", zhuyin: { symbol: "ㄕˋ" } },
  { char: "個", zhuyin: { symbol: "ㄍㄜ˙" } },
  { char: "人", zhuyin: { symbol: "ㄖㄣˊ" } },
  { char: "有", zhuyin: { symbol: "ㄧㄡˇ" } },
  { char: "太", zhuyin: { symbol: "ㄊㄞˋ" } },
  { char: "很", zhuyin: { symbol: "ㄏㄣˇ" } },
  { char: "好", zhuyin: { symbol: "ㄏㄠˇ" } },
  { char: "吃", zhuyin: { symbol: "ㄔ" } },
  { char: "喝", zhuyin: { symbol: "ㄏㄜ" } },
  { char: "水", zhuyin: { symbol: "ㄕㄨㄟˇ" } },
  { char: "要", zhuyin: { symbol: "ㄧㄠˋ" } },
  { char: "什", zhuyin: { symbol: "ㄕㄣˊ" } },
  { char: "麼", zhuyin: { symbol: "ㄇㄜ˙" } },
  { char: "不", zhuyin: { symbol: "ㄅㄨˋ" } },
  { char: "嗎", zhuyin: { symbol: "ㄇㄚ˙" } },
  { char: "可", zhuyin: { symbol: "ㄎㄜˇ" } },
  { char: "以", zhuyin: { symbol: "ㄧˇ" } },
  { char: "謝", zhuyin: { symbol: "ㄒㄧㄝˋ" } },
  { char: "在", zhuyin: { symbol: "ㄗㄞˋ" } },
  { char: "這", zhuyin: { symbol: "ㄓㄜˋ" } },
  { char: "那", zhuyin: { symbol: "ㄋㄚˋ" } },
  { char: "的", zhuyin: { symbol: "ㄉㄜ˙" } },
  { char: "了", zhuyin: { symbol: "ㄌㄜ˙" } },
  { char: "跟", zhuyin: { symbol: "ㄍㄣ" } },
];

export const beginnerFamilySet = [
  { char: "爸", zhuyin: { symbol: "ㄅㄚˋ" } },
  { char: "媽", zhuyin: { symbol: "ㄇㄚ" } },
  { char: "哥", zhuyin: { symbol: "ㄍㄜ" } },
  { char: "姐", zhuyin: { symbol: "ㄐㄧㄝˇ" } },
  { char: "弟", zhuyin: { symbol: "ㄉㄧˋ" } },
  { char: "妹", zhuyin: { symbol: "ㄇㄟˋ" } },
  { char: "家", zhuyin: { symbol: "ㄐㄧㄚ" } },
  { char: "愛", zhuyin: { symbol: "ㄞˋ" } },
  { char: "人", zhuyin: { symbol: "ㄖㄣˊ" } },
  { char: "朋", zhuyin: { symbol: "ㄆㄥˊ" } },
  { char: "友", zhuyin: { symbol: "ㄧㄡˇ" } },
  { char: "孩", zhuyin: { symbol: "ㄏㄞˊ" } },
  { char: "子", zhuyin: { symbol: "ㄗ˙" } },
];

export const beginnerSchoolSet = [
  { char: "學", zhuyin: { symbol: "ㄒㄩㄝˊ" } },
  { char: "校", zhuyin: { symbol: "ㄒㄧㄠˋ" } },
  { char: "老", zhuyin: { symbol: "ㄌㄠˇ" } },
  { char: "師", zhuyin: { symbol: "ㄕ" } },
  { char: "生", zhuyin: { symbol: "ㄕㄥ" } },
  { char: "書", zhuyin: { symbol: "ㄕㄨ" } },
  { char: "課", zhuyin: { symbol: "ㄎㄜˋ" } },
  { char: "桌", zhuyin: { symbol: "ㄓㄨㄛ" } },
  { char: "筆", zhuyin: { symbol: "ㄅㄧˇ" } },
  { char: "包", zhuyin: { symbol: "ㄅㄠ" } },
  { char: "寫", zhuyin: { symbol: "ㄒㄧㄝˇ" } },
  { char: "讀", zhuyin: { symbol: "ㄉㄨˊ" } },
  { char: "考", zhuyin: { symbol: "ㄎㄠˇ" } },
  { char: "試", zhuyin: { symbol: "ㄕˋ" } },
];

export const beginnerTimeSet = [
  { char: "日", zhuyin: { symbol: "ㄖˋ" } },
  { char: "月", zhuyin: { symbol: "ㄩㄝˋ" } },
  { char: "年", zhuyin: { symbol: "ㄋㄧㄢˊ" } },
  { char: "天", zhuyin: { symbol: "ㄊㄧㄢ" } },
  { char: "早", zhuyin: { symbol: "ㄗㄠˇ" } },
  { char: "晚", zhuyin: { symbol: "ㄨㄢˇ" } },
  { char: "時", zhuyin: { symbol: "ㄕˊ" } },
  { char: "分", zhuyin: { symbol: "ㄈㄣ" } },
  { char: "鐘", zhuyin: { symbol: "ㄓㄨㄥ" } },
  { char: "今", zhuyin: { symbol: "ㄐㄧㄣ" } },
  { char: "明", zhuyin: { symbol: "ㄇㄧㄥˊ" } },
  { char: "昨", zhuyin: { symbol: "ㄗㄨㄛˊ" } },
];

export const beginnerActionSet = [
  { char: "走", zhuyin: { symbol: "ㄗㄡˇ" } },
  { char: "跑", zhuyin: { symbol: "ㄆㄠˇ" } },
  { char: "來", zhuyin: { symbol: "ㄌㄞˊ" } },
  { char: "去", zhuyin: { symbol: "ㄑㄩˋ" } },
  { char: "看", zhuyin: { symbol: "ㄎㄢˋ" } },
  { char: "聽", zhuyin: { symbol: "ㄊㄧㄥ" } },
  { char: "說", zhuyin: { symbol: "ㄕㄨㄛ" } },
  { char: "寫", zhuyin: { symbol: "ㄒㄧㄝˇ" } },
  { char: "讀", zhuyin: { symbol: "ㄉㄨˊ" } },
  { char: "做", zhuyin: { symbol: "ㄗㄨㄛˋ" } },
  { char: "開", zhuyin: { symbol: "ㄎㄞ" } },
  { char: "關", zhuyin: { symbol: "ㄍㄨㄢ" } },
  { char: "坐", zhuyin: { symbol: "ㄗㄨㄛˋ" } },
  { char: "起", zhuyin: { symbol: "ㄑㄧˇ" } },
  { char: "跳", zhuyin: { symbol: "ㄊㄧㄠˋ" } },
  { char: "玩", zhuyin: { symbol: "ㄨㄢˊ" } },
  { char: "愛", zhuyin: { symbol: "ㄞˋ" } },
];

export const beginnerNatureSet = [
  { char: "天", zhuyin: { symbol: "ㄊㄧㄢ" } },
  { char: "地", zhuyin: { symbol: "ㄉㄧˋ" } },
  { char: "山", zhuyin: { symbol: "ㄕㄢ" } },
  { char: "水", zhuyin: { symbol: "ㄕㄨㄟˇ" } },
  { char: "火", zhuyin: { symbol: "ㄏㄨㄛˇ" } },
  { char: "風", zhuyin: { symbol: "ㄈㄥ" } },
  { char: "雨", zhuyin: { symbol: "ㄩˇ" } },
  { char: "雲", zhuyin: { symbol: "ㄩㄣˊ" } },
  { char: "花", zhuyin: { symbol: "ㄏㄨㄚ" } },
  { char: "草", zhuyin: { symbol: "ㄘㄠˇ" } },
  { char: "木", zhuyin: { symbol: "ㄇㄨˋ" } },
  { char: "石", zhuyin: { symbol: "ㄕˊ" } },
  { char: "氣", zhuyin: { symbol: "ㄑㄧˋ" } },
];

export const beginnerPlaceSet = [
  { char: "家", zhuyin: { symbol: "ㄐㄧㄚ" } },
  { char: "學", zhuyin: { symbol: "ㄒㄩㄝˊ" } },
  { char: "校", zhuyin: { symbol: "ㄒㄧㄠˋ" } },
  { char: "公", zhuyin: { symbol: "ㄍㄨㄥ" } },
  { char: "園", zhuyin: { symbol: "ㄩㄢˊ" } },
  { char: "商", zhuyin: { symbol: "ㄕㄤ" } },
  { char: "店", zhuyin: { symbol: "ㄉㄧㄢˋ" } },
  { char: "醫", zhuyin: { symbol: "ㄧ" } },
  { char: "院", zhuyin: { symbol: "ㄩㄢˋ" } },
  { char: "車", zhuyin: { symbol: "ㄔㄜ" } },
  { char: "站", zhuyin: { symbol: "ㄓㄢˋ" } },
  { char: "圖", zhuyin: { symbol: "ㄊㄨˊ" } },
  { char: "書", zhuyin: { symbol: "ㄕㄨ" } },
  { char: "館", zhuyin: { symbol: "ㄍㄨㄢˇ" } },
  { char: "公", zhuyin: { symbol: "ㄍㄨㄥ" } },
  { char: "司", zhuyin: { symbol: "ㄙ" } },
  { char: "市", zhuyin: { symbol: "ㄕˋ" } },
  { char: "場", zhuyin: { symbol: "ㄔㄤˇ" } },
  { char: "飯", zhuyin: { symbol: "ㄈㄢˋ" } },
  { char: "店", zhuyin: { symbol: "ㄉㄧㄢˋ" } },
  { char: "外", zhuyin: { symbol: "ㄨㄞˋ" } },
  { char: "裡", zhuyin: { symbol: "ㄌㄧˇ" } },
];

export const beginnerAnimalSet = [
  { char: "狗", zhuyin: { symbol: "ㄍㄡˇ" } },
  { char: "貓", zhuyin: { symbol: "ㄇㄠ" } },
  { char: "鳥", zhuyin: { symbol: "ㄋㄧㄠˇ" } },
  { char: "魚", zhuyin: { symbol: "ㄩˊ" } },
  { char: "馬", zhuyin: { symbol: "ㄇㄚˇ" } },
  { char: "牛", zhuyin: { symbol: "ㄋㄧㄡˊ" } },
  { char: "羊", zhuyin: { symbol: "ㄧㄤˊ" } },
  { char: "豬", zhuyin: { symbol: "ㄓㄨ" } },
  { char: "兔", zhuyin: { symbol: "ㄊㄨˋ" } },
  { char: "熊", zhuyin: { symbol: "ㄒㄩㄥˊ" } },
];

export const beginnerColorSet = [
  { char: "紅", zhuyin: { symbol: "ㄏㄨㄥˊ" } },
  { char: "藍", zhuyin: { symbol: "ㄌㄢˊ" } },
  { char: "黃", zhuyin: { symbol: "ㄏㄨㄤˊ" } },
  { char: "綠", zhuyin: { symbol: "ㄌㄩˋ" } },
  { char: "黑", zhuyin: { symbol: "ㄏㄟ" } },
  { char: "白", zhuyin: { symbol: "ㄅㄞˊ" } },
  { char: "紫", zhuyin: { symbol: "ㄗˇ" } },
  { char: "粉", zhuyin: { symbol: "ㄈㄣˇ" } },
  { char: "色", zhuyin: { symbol: "ㄙㄜˋ" } },
];

export const beginnerNumberSet = [
  { char: "零", zhuyin: { symbol: "ㄌㄧㄥˊ" } },
  { char: "一", zhuyin: { symbol: "ㄧ" } },
  { char: "二", zhuyin: { symbol: "ㄦˋ" } },
  { char: "三", zhuyin: { symbol: "ㄙㄢ" } },
  { char: "四", zhuyin: { symbol: "ㄙˋ" } },
  { char: "五", zhuyin: { symbol: "ㄨˇ" } },
  { char: "六", zhuyin: { symbol: "ㄌㄧㄡˋ" } },
  { char: "七", zhuyin: { symbol: "ㄑㄧ" } },
  { char: "八", zhuyin: { symbol: "ㄅㄚ" } },
  { char: "九", zhuyin: { symbol: "ㄐㄧㄡˇ" } },
  { char: "十", zhuyin: { symbol: "ㄕˊ" } },
  { char: "幾", zhuyin: { symbol: "ㄐㄧˇ" } },
  { char: "多", zhuyin: { symbol: "ㄉㄨㄛ" } },
  { char: "少", zhuyin: { symbol: "ㄕㄠˇ" } },
];

export const beginnerFoodSet = [
  { char: "米", zhuyin: { symbol: "ㄇㄧˇ" } },
  { char: "麵", zhuyin: { symbol: "ㄇㄧㄢˋ" } },
  { char: "蛋", zhuyin: { symbol: "ㄉㄢˋ" } },
  { char: "肉", zhuyin: { symbol: "ㄖㄡˋ" } },
  { char: "菜", zhuyin: { symbol: "ㄘㄞˋ" } },
  { char: "魚", zhuyin: { symbol: "ㄩˊ" } },
  { char: "豆", zhuyin: { symbol: "ㄉㄡˋ" } },
  { char: "奶", zhuyin: { symbol: "ㄋㄞˇ" } },
  { char: "糖", zhuyin: { symbol: "ㄊㄤˊ" } },
  { char: "油", zhuyin: { symbol: "ㄧㄡˊ" } },
  { char: "鹽", zhuyin: { symbol: "ㄧㄢˊ" } },
  { char: "果", zhuyin: { symbol: "ㄍㄨㄛˇ" } },
  { char: "包", zhuyin: { symbol: "ㄅㄠ" } },
];

// COMPOSITE SETS

export const beginnerSet = [
  ...pronounSet,
  ...basicSet,
  ...beginnerFamilySet,
  ...beginnerSchoolSet,
  ...beginnerTimeSet,
  ...beginnerActionSet,
  ...beginnerNatureSet,
  ...beginnerPlaceSet,
  ...beginnerAnimalSet,
  ...beginnerColorSet,
  ...beginnerNumberSet,
  ...beginnerFoodSet,
];
