export const pronounSet = [
  { char: "我", zhuyin: "ㄨㄛˇ" },
  { char: "你", zhuyin: "ㄋㄧˇ" },
  { char: "他", zhuyin: "ㄊㄚ" },
  { char: "她", zhuyin: "ㄊㄚ" },
  { char: "們", zhuyin: "ㄇㄣ˙" },
];

export const basicSet = [
  { char: "是", zhuyin: "ㄕˋ" },
  { char: "個", zhuyin: "ㄍㄜ˙" },
  { char: "人", zhuyin: "ㄖㄣˊ" },
  { char: "有", zhuyin: "ㄧㄡˇ" },
  { char: "太", zhuyin: "ㄊㄞˋ" },
  { char: "很", zhuyin: "ㄏㄣˇ" },
  { char: "好", zhuyin: "ㄏㄠˇ" },
  { char: "吃", zhuyin: "ㄔ" },
  { char: "喝", zhuyin: "ㄏㄜ" },
  { char: "水", zhuyin: "ㄕㄨㄟˇ" },
  { char: "要", zhuyin: "ㄧㄠˋ" },
  { char: "什", zhuyin: "ㄕㄣˊ" },
  { char: "麼", zhuyin: "ㄇㄜ˙" },
  { char: "不", zhuyin: "ㄅㄨˋ" },
  { char: "嗎", zhuyin: "ㄇㄚ˙" },
  { char: "可", zhuyin: "ㄎㄜˇ" },
  { char: "以", zhuyin: "ㄧˇ" },
  { char: "謝", zhuyin: "ㄒㄧㄝˋ" },
  { char: "在", zhuyin: "ㄗㄞˋ" },
  { char: "這", zhuyin: "ㄓㄜˋ" },
  { char: "那", zhuyin: "ㄋㄚˋ" },
  { char: "的", zhuyin: "ㄉㄜ˙" },
  { char: "了", zhuyin: "ㄌㄜ˙" },
  { char: "跟", zhuyin: "ㄍㄣ" },
];

export const beginnerFamilySet = [
  { char: "爸", zhuyin: "ㄅㄚˋ" },
  { char: "媽", zhuyin: "ㄇㄚ" },
  { char: "哥", zhuyin: "ㄍㄜ" },
  { char: "姐", zhuyin: "ㄐㄧㄝˇ" },
  { char: "弟", zhuyin: "ㄉㄧˋ" },
  { char: "妹", zhuyin: "ㄇㄟˋ" },
  { char: "家", zhuyin: "ㄐㄧㄚ" },
  { char: "愛", zhuyin: "ㄞˋ" },
  { char: "人", zhuyin: "ㄖㄣˊ" },
  { char: "朋", zhuyin: "ㄆㄥˊ" },
  { char: "友", zhuyin: "ㄧㄡˇ" },
  { char: "孩", zhuyin: "ㄏㄞˊ" },
  { char: "子", zhuyin: "ㄗ˙" },
];

export const beginnerSchoolSet = [
  { char: "學", zhuyin: "ㄒㄩㄝˊ" },
  { char: "校", zhuyin: "ㄒㄧㄠˋ" },
  { char: "老", zhuyin: "ㄌㄠˇ" },
  { char: "師", zhuyin: "ㄕ" },
  { char: "生", zhuyin: "ㄕㄥ" },
  { char: "書", zhuyin: "ㄕㄨ" },
  { char: "課", zhuyin: "ㄎㄜˋ" },
  { char: "桌", zhuyin: "ㄓㄨㄛ" },
  { char: "筆", zhuyin: "ㄅㄧˇ" },
  { char: "包", zhuyin: "ㄅㄠ" },
  { char: "寫", zhuyin: "ㄒㄧㄝˇ" },
  { char: "讀", zhuyin: "ㄉㄨˊ" },
  { char: "考", zhuyin: "ㄎㄠˇ" },
  { char: "試", zhuyin: "ㄕˋ" },
];

export const beginnerTimeSet = [
  { char: "日", zhuyin: "ㄖˋ" },
  { char: "月", zhuyin: "ㄩㄝˋ" },
  { char: "年", zhuyin: "ㄋㄧㄢˊ" },
  { char: "天", zhuyin: "ㄊㄧㄢ" },
  { char: "早", zhuyin: "ㄗㄠˇ" },
  { char: "晚", zhuyin: "ㄨㄢˇ" },
  { char: "時", zhuyin: "ㄕˊ" },
  { char: "分", zhuyin: "ㄈㄣ" },
  { char: "鐘", zhuyin: "ㄓㄨㄥ" },
  { char: "今", zhuyin: "ㄐㄧㄣ" },
  { char: "明", zhuyin: "ㄇㄧㄥˊ" },
  { char: "昨", zhuyin: "ㄗㄨㄛˊ" },
];

export const beginnerActionSet = [
  { char: "走", zhuyin: "ㄗㄡˇ" },
  { char: "跑", zhuyin: "ㄆㄠˇ" },
  { char: "來", zhuyin: "ㄌㄞˊ" },
  { char: "去", zhuyin: "ㄑㄩˋ" },
  { char: "看", zhuyin: "ㄎㄢˋ" },
  { char: "聽", zhuyin: "ㄊㄧㄥ" },
  { char: "說", zhuyin: "ㄕㄨㄛ" },
  { char: "寫", zhuyin: "ㄒㄧㄝˇ" },
  { char: "讀", zhuyin: "ㄉㄨˊ" },
  { char: "做", zhuyin: "ㄗㄨㄛˋ" },
  { char: "開", zhuyin: "ㄎㄞ" },
  { char: "關", zhuyin: "ㄍㄨㄢ" },
  { char: "坐", zhuyin: "ㄗㄨㄛˋ" },
  { char: "起", zhuyin: "ㄑㄧˇ" },
  { char: "跳", zhuyin: "ㄊㄧㄠˋ" },
  { char: "玩", zhuyin: "ㄨㄢˊ" },
  { char: "愛", zhuyin: "ㄞˋ" },
];

export const beginnerNatureSet = [
  { char: "天", zhuyin: "ㄊㄧㄢ" },
  { char: "地", zhuyin: "ㄉㄧˋ" },
  { char: "山", zhuyin: "ㄕㄢ" },
  { char: "水", zhuyin: "ㄕㄨㄟˇ" },
  { char: "火", zhuyin: "ㄏㄨㄛˇ" },
  { char: "風", zhuyin: "ㄈㄥ" },
  { char: "雨", zhuyin: "ㄩˇ" },
  { char: "雲", zhuyin: "ㄩㄣˊ" },
  { char: "花", zhuyin: "ㄏㄨㄚ" },
  { char: "草", zhuyin: "ㄘㄠˇ" },
  { char: "木", zhuyin: "ㄇㄨˋ" },
  { char: "石", zhuyin: "ㄕˊ" },
  { char: "氣", zhuyin: "ㄑㄧˋ" },
];

export const beginnerPlaceSet = [
  { char: "家", zhuyin: "ㄐㄧㄚ" },
  { char: "學", zhuyin: "ㄒㄩㄝˊ" },
  { char: "校", zhuyin: "ㄒㄧㄠˋ" },
  { char: "公", zhuyin: "ㄍㄨㄥ" },
  { char: "園", zhuyin: "ㄩㄢˊ" },
  { char: "商", zhuyin: "ㄕㄤ" },
  { char: "店", zhuyin: "ㄉㄧㄢˋ" },
  { char: "醫", zhuyin: "ㄧ" },
  { char: "院", zhuyin: "ㄩㄢˋ" },
  { char: "車", zhuyin: "ㄔㄜ" },
  { char: "站", zhuyin: "ㄓㄢˋ" },
  { char: "圖", zhuyin: "ㄊㄨˊ" },
  { char: "書", zhuyin: "ㄕㄨ" },
  { char: "館", zhuyin: "ㄍㄨㄢˇ" },
  { char: "公", zhuyin: "ㄍㄨㄥ" },
  { char: "司", zhuyin: "ㄙ" },
  { char: "市", zhuyin: "ㄕˋ" },
  { char: "場", zhuyin: "ㄔㄤˇ" },
  { char: "飯", zhuyin: "ㄈㄢˋ" },
  { char: "店", zhuyin: "ㄉㄧㄢˋ" },
  { char: "外", zhuyin: "ㄨㄞˋ" },
  { char: "裡", zhuyin: "ㄌㄧˇ" },
];

export const beginnerAnimalSet = [
  { char: "狗", zhuyin: "ㄍㄡˇ" },
  { char: "貓", zhuyin: "ㄇㄠ" },
  { char: "鳥", zhuyin: "ㄋㄧㄠˇ" },
  { char: "魚", zhuyin: "ㄩˊ" },
  { char: "馬", zhuyin: "ㄇㄚˇ" },
  { char: "牛", zhuyin: "ㄋㄧㄡˊ" },
  { char: "羊", zhuyin: "ㄧㄤˊ" },
  { char: "豬", zhuyin: "ㄓㄨ" },
  { char: "兔", zhuyin: "ㄊㄨˋ" },
  { char: "熊", zhuyin: "ㄒㄩㄥˊ" },
];

export const beginnerColorSet = [
  { char: "紅", zhuyin: "ㄏㄨㄥˊ" },
  { char: "藍", zhuyin: "ㄌㄢˊ" },
  { char: "黃", zhuyin: "ㄏㄨㄤˊ" },
  { char: "綠", zhuyin: "ㄌㄩˋ" },
  { char: "黑", zhuyin: "ㄏㄟ" },
  { char: "白", zhuyin: "ㄅㄞˊ" },
  { char: "紫", zhuyin: "ㄗˇ" },
  { char: "粉", zhuyin: "ㄈㄣˇ" },
  { char: "色", zhuyin: "ㄙㄜˋ" },
];

export const beginnerNumberSet = [
  { char: "零", zhuyin: "ㄌㄧㄥˊ" },
  { char: "一", zhuyin: "ㄧ" },
  { char: "二", zhuyin: "ㄦˋ" },
  { char: "三", zhuyin: "ㄙㄢ" },
  { char: "四", zhuyin: "ㄙˋ" },
  { char: "五", zhuyin: "ㄨˇ" },
  { char: "六", zhuyin: "ㄌㄧㄡˋ" },
  { char: "七", zhuyin: "ㄑㄧ" },
  { char: "八", zhuyin: "ㄅㄚ" },
  { char: "九", zhuyin: "ㄐㄧㄡˇ" },
  { char: "十", zhuyin: "ㄕˊ" },
  { char: "幾", zhuyin: "ㄐㄧˇ" },
  { char: "多", zhuyin: "ㄉㄨㄛ" },
  { char: "少", zhuyin: "ㄕㄠˇ" },
];

export const beginnerFoodSet = [
  { char: "米", zhuyin: "ㄇㄧˇ" },
  { char: "麵", zhuyin: "ㄇㄧㄢˋ" },
  { char: "蛋", zhuyin: "ㄉㄢˋ" },
  { char: "肉", zhuyin: "ㄖㄡˋ" },
  { char: "菜", zhuyin: "ㄘㄞˋ" },
  { char: "魚", zhuyin: "ㄩˊ" },
  { char: "豆", zhuyin: "ㄉㄡˋ" },
  { char: "奶", zhuyin: "ㄋㄞˇ" },
  { char: "糖", zhuyin: "ㄊㄤˊ" },
  { char: "油", zhuyin: "ㄧㄡˊ" },
  { char: "鹽", zhuyin: "ㄧㄢˊ" },
  { char: "果", zhuyin: "ㄍㄨㄛˇ" },
  { char: "包", zhuyin: "ㄅㄠ" },
];

// COMPOSITE SETS

export const beginnerSet = [
  ...pronounSet,
  ...basicSet,
  ...beginnerFamilySet,
  ...beginnerSchoolSet,
  ...beginnerTimeSet,
  ...beginnerActionSet,
  ...beginnerNatureSet,
  ...beginnerPlaceSet,
  ...beginnerAnimalSet,
  ...beginnerColorSet,
  ...beginnerNumberSet,
  ...beginnerFoodSet,
];
