const basicPronounSet = [
  { char: "我", zhuyin: "ㄨㄛˇ" },
  { char: "你", zhuyin: "ㄋㄧˇ" },
  { char: "他", zhuyin: "ㄊㄚ " },
  { char: "她", zhuyin: "ㄊㄚ " },
  { char: "它", zhuyin: "ㄊㄚ " },
  { char: "們", zhuyin: "ㄇㄣ˙" },
];

const basicNumberSet = [
  { char: "零", zhuyin: "ㄌㄧㄥˊ" },
  { char: "一", zhuyin: "ㄧ " },
  { char: "二", zhuyin: "ㄦˋ" },
  { char: "三", zhuyin: "ㄙㄢ " },
  { char: "四", zhuyin: "ㄙˋ" },
  { char: "五", zhuyin: "ㄨˇ" },
  { char: "六", zhuyin: "ㄌㄧㄡˋ" },
  { char: "七", zhuyin: "ㄑㄧ " },
  { char: "八", zhuyin: "ㄅㄚ " },
  { char: "九", zhuyin: "ㄐㄧㄡˇ" },
  { char: "十", zhuyin: "ㄕˊ" },
  { char: "幾", zhuyin: "ㄐㄧˇ" },
  { char: "多", zhuyin: "ㄉㄨㄛ " },
  { char: "少", zhuyin: "ㄕㄠˇ" },
];

const basicVerbSet = [
  { char: "是", zhuyin: "ㄕˋ" },
  { char: "想", zhuyin: "ㄒㄧㄤˇ" },
  { char: "要", zhuyin: "ㄧㄠˋ" },
  { char: "吃", zhuyin: "ㄔ " },
  { char: "喝", zhuyin: "ㄏㄜ " },
  { char: "有", zhuyin: "ㄧㄡˇ" },
  { char: "不", zhuyin: "ㄅㄨˋ" },
  { char: "沒", zhuyin: "ㄇㄟˊ" },
  { char: "可", zhuyin: "ㄎㄜˇ" },
  { char: "以", zhuyin: "ㄧˇ" },
  { char: "在", zhuyin: "ㄗㄞˋ" },
  { char: "謝", zhuyin: "ㄒㄧㄝˋ" },
  { char: "說", zhuyin: "ㄕㄨㄛ " },
  { char: "學", zhuyin: "ㄒㄩㄝˊ" },
  { char: "喜", zhuyin: "ㄒㄧˇ" },
  { char: "歡", zhuyin: "ㄏㄨㄢ " },
  { char: "和", zhuyin: "ㄏㄜˊ" },
];

const basicPeopleSet = [
  { char: "人", zhuyin: "ㄖㄣˊ" },
  { char: "朋", zhuyin: "ㄆㄥˊ" },
  { char: "友", zhuyin: "ㄧㄡˇ" },
  { char: "爸", zhuyin: "ㄅㄚˋ" },
  { char: "媽", zhuyin: "ㄇㄚ " },
  { char: "哥", zhuyin: "ㄍㄜ " },
  { char: "姐", zhuyin: "ㄐㄧㄝˇ" },
  { char: "弟", zhuyin: "ㄉㄧˋ" },
  { char: "妹", zhuyin: "ㄇㄟˋ" },
  { char: "家", zhuyin: "ㄐㄧㄚ " },
  { char: "老", zhuyin: "ㄌㄠˇ" },
  { char: "師", zhuyin: "ㄕ " },
];

const basicNounSet = [
  { char: "水", zhuyin: "ㄕㄨㄟˇ" },
  { char: "口", zhuyin: "ㄎㄡˇ" },
  { char: "書", zhuyin: "ㄕㄨ " },
  { char: "車", zhuyin: "ㄔㄜ " },
  { char: "茶", zhuyin: "ㄔㄚˊ" },
  { char: "牛", zhuyin: "ㄋㄧㄡˊ" },
  { char: "豬", zhuyin: "ㄓㄨ " },
  { char: "雞", zhuyin: "ㄐㄧ " },
  { char: "肉", zhuyin: "ㄖㄡˋ" },
  { char: "米", zhuyin: "ㄇㄧˇ" },
  { char: "飯", zhuyin: "ㄈㄢˋ" },
  { char: "菜", zhuyin: "ㄘㄞˋ" },
  { char: "麵", zhuyin: "ㄇㄧㄢˋ" },
];

const basicColorSet = [
  { char: "色", zhuyin: "ㄙㄜˋ" },
  { char: "紅", zhuyin: "ㄏㄨㄥˊ" },
  { char: "藍", zhuyin: "ㄌㄢˊ" },
  { char: "黃", zhuyin: "ㄏㄨㄤˊ" },
  { char: "綠", zhuyin: "ㄌㄩˋ" },
  { char: "黑", zhuyin: "ㄏㄟ " },
  { char: "白", zhuyin: "ㄅㄞˊ" },
];

const basicMiscSet = [
  { char: "個", zhuyin: "ㄍㄜ˙" },
  { char: "太", zhuyin: "ㄊㄞˋ" },
  { char: "很", zhuyin: "ㄏㄣˇ" },
  { char: "好", zhuyin: "ㄏㄠˇ" },
  { char: "什", zhuyin: "ㄕㄣˊ" },
  { char: "麼", zhuyin: "ㄇㄜ˙" },
  { char: "錯", zhuyin: "ㄘㄨㄛˋ" },
  { char: "嗎", zhuyin: "ㄇㄚ˙" },
  { char: "這", zhuyin: "ㄓㄜˋ" },
  { char: "那", zhuyin: "ㄋㄚˋ" },
  { char: "的", zhuyin: "ㄉㄜ˙" },
  { char: "了", zhuyin: "ㄌㄜ˙" },
  { char: "上", zhuyin: "ㄕㄤˋ" },
  { char: "下", zhuyin: "ㄒㄧㄚˋ" },
  { char: "生", zhuyin: "ㄕㄥ " },
];

const beginnerSchoolAddOn = [
  { char: "學", zhuyin: "ㄒㄩㄝˊ" },
  { char: "校", zhuyin: "ㄒㄧㄠˋ" },
  { char: "生", zhuyin: "ㄕㄥ " },
  { char: "書", zhuyin: "ㄕㄨ " },
  { char: "課", zhuyin: "ㄎㄜˋ" },
  { char: "桌", zhuyin: "ㄓㄨㄛ " },
  { char: "筆", zhuyin: "ㄅㄧˇ" },
  { char: "包", zhuyin: "ㄅㄠ " },
  { char: "寫", zhuyin: "ㄒㄧㄝˇ" },
  { char: "讀", zhuyin: "ㄉㄨˊ" },
  { char: "考", zhuyin: "ㄎㄠˇ" },
  { char: "試", zhuyin: "ㄕˋ" },
  { char: "孩", zhuyin: "ㄏㄞˊ" },
  { char: "子", zhuyin: "ㄗ˙" },
  { char: "男", zhuyin: "ㄋㄢˊ" },
  { char: "女", zhuyin: "ㄋㄩˇ" },
];

const beginnerTimeAddOn = [
  { char: "日", zhuyin: "ㄖˋ" },
  { char: "月", zhuyin: "ㄩㄝˋ" },
  { char: "年", zhuyin: "ㄋㄧㄢˊ" },
  { char: "天", zhuyin: "ㄊㄧㄢ " },
  { char: "早", zhuyin: "ㄗㄠˇ" },
  { char: "晚", zhuyin: "ㄨㄢˇ" },
  { char: "時", zhuyin: "ㄕˊ" },
  { char: "分", zhuyin: "ㄈㄣ " },
  { char: "鐘", zhuyin: "ㄓㄨㄥ " },
  { char: "今", zhuyin: "ㄐㄧㄣ " },
  { char: "明", zhuyin: "ㄇㄧㄥˊ" },
  { char: "昨", zhuyin: "ㄗㄨㄛˊ" },
];

const beginnerActionAddOn = [
  { char: "走", zhuyin: "ㄗㄡˇ" },
  { char: "跑", zhuyin: "ㄆㄠˇ" },
  { char: "來", zhuyin: "ㄌㄞˊ" },
  { char: "去", zhuyin: "ㄑㄩˋ" },
  { char: "看", zhuyin: "ㄎㄢˋ" },
  { char: "聽", zhuyin: "ㄊㄧㄥ " },
  { char: "說", zhuyin: "ㄕㄨㄛ " },
  { char: "寫", zhuyin: "ㄒㄧㄝˇ" },
  { char: "讀", zhuyin: "ㄉㄨˊ" },
  { char: "做", zhuyin: "ㄗㄨㄛˋ" },
  { char: "開", zhuyin: "ㄎㄞ " },
  { char: "關", zhuyin: "ㄍㄨㄢ " },
  { char: "坐", zhuyin: "ㄗㄨㄛˋ" },
  { char: "起", zhuyin: "ㄑㄧˇ" },
  { char: "跳", zhuyin: "ㄊㄧㄠˋ" },
  { char: "玩", zhuyin: "ㄨㄢˊ" },
  { char: "愛", zhuyin: "ㄞˋ" },
  { char: "到", zhuyin: "ㄉㄠˋ" },
  { char: "跟", zhuyin: "ㄍㄣ " },
];

const beginnerNatureAddOn = [
  { char: "天", zhuyin: "ㄊㄧㄢ " },
  { char: "地", zhuyin: "ㄉㄧˋ" },
  { char: "山", zhuyin: "ㄕㄢ " },
  { char: "火", zhuyin: "ㄏㄨㄛˇ" },
  { char: "風", zhuyin: "ㄈㄥ " },
  { char: "雨", zhuyin: "ㄩˇ" },
  { char: "雲", zhuyin: "ㄩㄣˊ" },
  { char: "花", zhuyin: "ㄏㄨㄚ " },
  { char: "草", zhuyin: "ㄘㄠˇ" },
  { char: "木", zhuyin: "ㄇㄨˋ" },
  { char: "石", zhuyin: "ㄕˊ" },
  { char: "頭", zhuyin: "ㄊㄡˊ" },
  { char: "氣", zhuyin: "ㄑㄧˋ" },
];

const beginnerPlaceAddOn = [
  { char: "學", zhuyin: "ㄒㄩㄝˊ" },
  { char: "校", zhuyin: "ㄒㄧㄠˋ" },
  { char: "公", zhuyin: "ㄍㄨㄥ " },
  { char: "園", zhuyin: "ㄩㄢˊ" },
  { char: "商", zhuyin: "ㄕㄤ " },
  { char: "店", zhuyin: "ㄉㄧㄢˋ" },
  { char: "醫", zhuyin: "ㄧ " },
  { char: "院", zhuyin: "ㄩㄢˋ" },
  { char: "車", zhuyin: "ㄔㄜ " },
  { char: "站", zhuyin: "ㄓㄢˋ" },
  { char: "圖", zhuyin: "ㄊㄨˊ" },
  { char: "書", zhuyin: "ㄕㄨ " },
  { char: "館", zhuyin: "ㄍㄨㄢˇ" },
  { char: "公", zhuyin: "ㄍㄨㄥ " },
  { char: "司", zhuyin: "ㄙ " },
  { char: "市", zhuyin: "ㄕˋ" },
  { char: "場", zhuyin: "ㄔㄤˇ" },
  { char: "飯", zhuyin: "ㄈㄢˋ" },
  { char: "店", zhuyin: "ㄉㄧㄢˋ" },
  { char: "外", zhuyin: "ㄨㄞˋ" },
  { char: "裡", zhuyin: "ㄌㄧˇ" },
  { char: "面", zhuyin: "ㄇㄧㄢˋ" },
  { char: "哪", zhuyin: "ㄋㄚˇ" },
  { char: "台", zhuyin: "ㄊㄞˊ" },
  { char: "灣", zhuyin: "ㄨㄢ " },
  { char: "美", zhuyin: "ㄇㄟˇ" },
  { char: "國", zhuyin: "ㄍㄨㄛˊ" },
];

const beginnerAnimalAddOn = [
  { char: "狗", zhuyin: "ㄍㄡˇ" },
  { char: "貓", zhuyin: "ㄇㄠ " },
  { char: "鳥", zhuyin: "ㄋㄧㄠˇ" },
  { char: "魚", zhuyin: "ㄩˊ" },
  { char: "馬", zhuyin: "ㄇㄚˇ" },
  { char: "羊", zhuyin: "ㄧㄤˊ" },
];

const beginnerColorAddOn = [
  { char: "紫", zhuyin: "ㄗˇ" },
  { char: "粉", zhuyin: "ㄈㄣˇ" },
];

const beginnerFoodAddOn = [
  { char: "蛋", zhuyin: "ㄉㄢˋ" },
  { char: "豆", zhuyin: "ㄉㄡˋ" },
  { char: "奶", zhuyin: "ㄋㄞˇ" },
  { char: "果", zhuyin: "ㄍㄨㄛˇ" },
  { char: "蘋", zhuyin: "ㄆㄧㄥˊ" },
  { char: "芒", zhuyin: "ㄇㄤˊ" },
  { char: "草", zhuyin: "ㄘㄠˇ" },
  { char: "莓", zhuyin: "ㄇㄟˊ" },
  { char: "包", zhuyin: "ㄅㄠ " },
  { char: "餃", zhuyin: "ㄐㄧㄠˇ" },
];

const intermediateCharAddOn = [
  { char: "對", zhuyin: "ㄉㄨㄟˋ" },
  { char: "過", zhuyin: "ㄍㄨㄛˋ" },
  { char: "難", zhuyin: "ㄋㄢˊ" },
  { char: "變", zhuyin: "ㄅㄧㄢˋ" },
  { char: "畫", zhuyin: "ㄏㄨㄚˋ" },
  { char: "轉", zhuyin: "ㄓㄨㄢˇ" },
  { char: "續", zhuyin: "ㄒㄩˋ" },
  { char: "運", zhuyin: "ㄩㄣˋ" },
  { char: "銀", zhuyin: "ㄧㄣˊ" },
  { char: "飲", zhuyin: "ㄧㄣˇ" },
  { char: "難", zhuyin: "ㄋㄢˊ" },
  { char: "關", zhuyin: "ㄍㄨㄢ " },
  { char: "機", zhuyin: "ㄐㄧ " },
  { char: "圖", zhuyin: "ㄊㄨˊ" },
  { char: "館", zhuyin: "ㄍㄨㄢˇ" },
  { char: "隊", zhuyin: "ㄉㄨㄟˋ" },
  { char: "請", zhuyin: "ㄑㄧㄥˇ" },
  { char: "待", zhuyin: "ㄉㄞˋ" },
  { char: "改", zhuyin: "ㄍㄞˇ" },
  { char: "整", zhuyin: "ㄓㄥˇ" },
  { char: "決", zhuyin: "ㄐㄩㄝˊ" },
  { char: "話", zhuyin: "ㄏㄨㄚˋ" },
  { char: "題", zhuyin: "ㄊㄧˊ" },
  { char: "解", zhuyin: "ㄐㄧㄝˇ" },
  { char: "問", zhuyin: "ㄨㄣˋ" },
  { char: "答", zhuyin: "ㄉㄚˊ" },
  { char: "辦", zhuyin: "ㄅㄢˋ" },
  { char: "法", zhuyin: "ㄈㄚˇ" },
  { char: "權", zhuyin: "ㄑㄩㄢˊ" },
  { char: "利", zhuyin: "ㄌㄧˋ" },
  { char: "據", zhuyin: "ㄐㄩˋ" },
  { char: "報", zhuyin: "ㄅㄠˋ" },
  { char: "導", zhuyin: "ㄉㄠˇ" },
  { char: "演", zhuyin: "ㄧㄢˇ" },
  { char: "響", zhuyin: "ㄒㄧㄤˇ" },
  { char: "像", zhuyin: "ㄒㄧㄤˋ" },
  { char: "環", zhuyin: "ㄏㄨㄢˊ" },
  { char: "境", zhuyin: "ㄐㄧㄥˋ" },
  { char: "資", zhuyin: "ㄗ " },
  { char: "源", zhuyin: "ㄩㄢˊ" },
  { char: "需", zhuyin: "ㄒㄩ " },
  { char: "究", zhuyin: "ㄐㄧㄡ " },
  { char: "竟", zhuyin: "ㄐㄧㄥˋ" },
  { char: "致", zhuyin: "ㄓˋ" },
  { char: "節", zhuyin: "ㄐㄧㄝˊ" },
  { char: "稱", zhuyin: "ㄔㄥ " },
  { char: "該", zhuyin: "ㄍㄞ " },
  { char: "勢", zhuyin: "ㄕˋ" },
  { char: "伴", zhuyin: "ㄅㄢˋ" },
  { char: "系", zhuyin: "ㄒㄧˋ" },
  { char: "劇", zhuyin: "ㄐㄩˋ" },
  { char: "段", zhuyin: "ㄉㄨㄢˋ" },
  { char: "快", zhuyin: "ㄎㄨㄞˋ" },
  { char: "慢", zhuyin: "ㄇㄢˋ" },
  { char: "優", zhuyin: "ㄧㄡ " },
  { char: "秀", zhuyin: "ㄒㄧㄡˋ" },
  { char: "選", zhuyin: "ㄒㄩㄢˇ" },
  { char: "擇", zhuyin: "ㄗㄜˊ" },
  { char: "擔", zhuyin: "ㄉㄢ " },
  { char: "負", zhuyin: "ㄈㄨˋ" },
  { char: "責", zhuyin: "ㄗㄜˊ" },
  { char: "察", zhuyin: "ㄔㄚˊ" },
  { char: "典", zhuyin: "ㄉㄧㄢˇ" },
  { char: "準", zhuyin: "ㄓㄨㄣˇ" },
  { char: "備", zhuyin: "ㄅㄟˋ" },
  { char: "料", zhuyin: "ㄌㄧㄠˋ" },
  { char: "慎", zhuyin: "ㄕㄣˋ" },
  { char: "薦", zhuyin: "ㄐㄧㄢˋ" },
  { char: "激", zhuyin: "ㄐㄧ " },
  { char: "載", zhuyin: "ㄗㄞˋ" },
  { char: "跨", zhuyin: "ㄎㄨㄚˋ" },
  { char: "孫", zhuyin: "ㄙㄨㄣ " },
  { char: "胞", zhuyin: "ㄅㄠ " },
  { char: "廷", zhuyin: "ㄊㄧㄥ " },
  { char: "倒", zhuyin: "ㄉㄠˇ" },
  { char: "歧", zhuyin: "ㄑㄧˊ" },
  { char: "視", zhuyin: "ㄕˋ" },
  { char: "打", zhuyin: "ㄉㄚˇ" },
  { char: "敗", zhuyin: "ㄅㄞ " },
  { char: "迫", zhuyin: "ㄆㄛˋ" },
  { char: "賞", zhuyin: "ㄕㄤˇ" },
  { char: "狀", zhuyin: "ㄓㄨㄤˋ" },
  { char: "慮", zhuyin: "ㄌㄩˋ" },
  { char: "橋", zhuyin: "ㄑㄧㄠˊ" },
  { char: "幅", zhuyin: "ㄈㄨˊ" },
  { char: "篇", zhuyin: "ㄆㄧㄢ " },
  { char: "冒", zhuyin: "ㄇㄠˋ" },
  { char: "露", zhuyin: "ㄌㄨˋ" },
  { char: "兔", zhuyin: "ㄊㄨˋ" },
  { char: "熊", zhuyin: "ㄒㄩㄥˊ" },
  { char: "糖", zhuyin: "ㄊㄤˊ" },
  { char: "油", zhuyin: "ㄧㄡˊ" },
  { char: "鹽", zhuyin: "ㄧㄢˊ" },
  { char: "臺", zhuyin: "ㄊㄞˊ" },
];

const intermediateArticleAddOn = [
  { char: "呢", zhuyin: "ㄋㄜ˙" },
  { char: "吧", zhuyin: "ㄅㄚ˙" },
  { char: "啊", zhuyin: "ㄚ˙" },
  { char: "哦", zhuyin: "ㄛˋ" },
];

const advancedCharAddOn = [
  { char: "懼", zhuyin: "ㄐㄩˋ" },
  { char: "縱", zhuyin: "ㄗㄨㄥˋ" },
  { char: "翻", zhuyin: "ㄈㄢ " },
  { char: "譯", zhuyin: "ㄧˋ" },
  { char: "憂", zhuyin: "ㄧㄡ " },
  { char: "顯", zhuyin: "ㄒㄧㄢˇ" },
  { char: "析", zhuyin: "ㄒㄧ " },
  { char: "媒", zhuyin: "ㄇㄟˊ" },
  { char: "體", zhuyin: "ㄊㄧˇ" },
  { char: "載", zhuyin: "ㄗㄞˋ" },
  { char: "層", zhuyin: "ㄘㄥˊ" },
  { char: "拓", zhuyin: "ㄊㄨㄛˋ" },
  { char: "增", zhuyin: "ㄗㄥ " },
  { char: "加", zhuyin: "ㄐㄧㄚ " },
  { char: "減", zhuyin: "ㄐㄧㄢˇ" },
  { char: "薦", zhuyin: "ㄐㄧㄢˋ" },
  { char: "韻", zhuyin: "ㄩㄣˋ" },
  { char: "錄", zhuyin: "ㄌㄨˋ" },
  { char: "慶", zhuyin: "ㄑㄧㄥˋ" },
  { char: "療", zhuyin: "ㄌㄧㄠˊ" },
  { char: "慣", zhuyin: "ㄍㄨㄢˋ" },
  { char: "徹", zhuyin: "ㄔㄜˋ" },
  { char: "臨", zhuyin: "ㄌㄧㄣˊ" },
  { char: "縫", zhuyin: "ㄈㄥˊ" },
  { char: "悍", zhuyin: "ㄏㄢˋ" },
  { char: "擾", zhuyin: "ㄖㄠˇ" },
  { char: "募", zhuyin: "ㄇㄨˋ" },
  { char: "冶", zhuyin: "ㄧㄝˇ" },
  { char: "惹", zhuyin: "ㄖㄜˇ" },
  { char: "漠", zhuyin: "ㄇㄛˋ" },
  { char: "駐", zhuyin: "ㄓㄨˋ" },
  { char: "斂", zhuyin: "ㄌㄧㄢˇ" },
  { char: "躍", zhuyin: "ㄩㄝˋ" },
  { char: "覆", zhuyin: "ㄈㄨˋ" },
  { char: "頹", zhuyin: "ㄊㄨㄟˊ" },
  { char: "惕", zhuyin: "ㄊㄧˋ" },
  { char: "鎖", zhuyin: "ㄙㄨㄛˇ" },
  { char: "裂", zhuyin: "ㄌㄧㄝˋ" },
  { char: "澄", zhuyin: "ㄔㄥˊ" },
  { char: "弧", zhuyin: "ㄏㄨˊ" },
  { char: "倘", zhuyin: "ㄊㄤˇ" },
  { char: "戲", zhuyin: "ㄒㄧˋ" },
  { char: "碑", zhuyin: "ㄅㄟ " },
  { char: "慈", zhuyin: "ㄘˊ" },
  { char: "邁", zhuyin: "ㄇㄞˋ" },
  { char: "烙", zhuyin: "ㄌㄠˋ" },
  { char: "墮", zhuyin: "ㄉㄨㄛˋ" },
  { char: "劫", zhuyin: "ㄐㄧㄝˊ" },
  { char: "搏", zhuyin: "ㄅㄛˊ" },
  { char: "挫", zhuyin: "ㄘㄨㄛˋ" },
  { char: "誓", zhuyin: "ㄕˋ" },
  { char: "憤", zhuyin: "ㄈㄣˋ" },
  { char: "盟", zhuyin: "ㄇㄥˊ" },
  { char: "懲", zhuyin: "ㄔㄥˊ" },
  { char: "脆", zhuyin: "ㄘㄨㄟˋ" },
  { char: "鞏", zhuyin: "ㄍㄨㄥˇ" },
  { char: "襲", zhuyin: "ㄒㄧˊ" },
  { char: "廉", zhuyin: "ㄌㄧㄢˊ" },
  { char: "緩", zhuyin: "ㄏㄨㄢˇ" },
  { char: "斑", zhuyin: "ㄅㄢ " },
  { char: "祿", zhuyin: "ㄌㄨˋ" },
  { char: "闊", zhuyin: "ㄎㄨㄛˋ" },
  { char: "竄", zhuyin: "ㄘㄨㄢˋ" },
  { char: "顫", zhuyin: "ㄓㄢˋ" },
  { char: "殲", zhuyin: "ㄐㄧㄢ " },
  { char: "焉", zhuyin: "ㄧㄢ " },
  { char: "珊", zhuyin: "ㄕㄢ " },
  { char: "峽", zhuyin: "ㄒㄧㄚˊ" },
  { char: "腥", zhuyin: "ㄒㄧㄥ " },
  { char: "妓", zhuyin: "ㄐㄧˋ" },
  { char: "憑", zhuyin: "ㄆㄧㄥˊ" },
  { char: "膠", zhuyin: "ㄐㄧㄠ " },
  { char: "窮", zhuyin: "ㄑㄩㄥˊ" },
  { char: "紮", zhuyin: "ㄓㄚ " },
  { char: "謀", zhuyin: "ㄇㄡˊ" },
  { char: "鏡", zhuyin: "ㄐㄧㄥˋ" },
  { char: "慕", zhuyin: "ㄇㄨ " },
  { char: "賦", zhuyin: "ㄈㄨˋ" },
  { char: "堵", zhuyin: "ㄉㄨˇ" },
  { char: "掘", zhuyin: "ㄐㄩㄝˊ" },
  { char: "險", zhuyin: "ㄒㄧㄢˇ" },
  { char: "恍", zhuyin: "ㄏㄨㄤˇ" },
  { char: "咆", zhuyin: "ㄆㄠˊ" },
  { char: "瑰", zhuyin: "ㄍㄨㄟ " },
  { char: "醞", zhuyin: "ㄩㄣˋ" },
  { char: "鬥", zhuyin: "ㄉㄡˋ" },
  { char: "鬧", zhuyin: "ㄋㄠˋ" },
];

const advancedArticleAddOn = [
  { char: "喔", zhuyin: "ㄛ˙" },
  { char: "唄", zhuyin: "ㄅㄟ˙" },
  { char: "诶", zhuyin: "ㄟ " },
  { char: "啦", zhuyin: "ㄌㄚ˙" },
  { char: "喽", zhuyin: "ㄌㄡ˙" },
];

const punctuationSet = [
  { char: "。", zhuyin: "`." },
  { char: "？", zhuyin: "`?" },
  { char: "！", zhuyin: "`!" },
  { char: "，", zhuyin: "`," },
  { char: "、", zhuyin: "`'" },
];

// COMPOSITE SETS

export const newbieSet = [
  ...basicPronounSet,
  ...basicNumberSet,
  ...basicVerbSet,
  ...basicPeopleSet,
  ...basicNounSet,
  ...basicColorSet,
  ...basicMiscSet,
  ...punctuationSet,
];

export const beginnerAddOnSet = [
  ...beginnerSchoolAddOn,
  ...beginnerTimeAddOn,
  ...beginnerActionAddOn,
  ...beginnerNatureAddOn,
  ...beginnerPlaceAddOn,
  ...beginnerAnimalAddOn,
  ...beginnerColorAddOn,
  ...beginnerFoodAddOn,
];

export const intermediateAddOnSet = [
  ...intermediateCharAddOn,
  ...intermediateArticleAddOn,
];

export const advancedAddOnSet = [
  ...advancedCharAddOn,
  ...advancedArticleAddOn,
];
