const basicPronounSet = [
  { char: "我", zhuyin: { symbol: "ㄨㄛˇ" } },
  { char: "你", zhuyin: { symbol: "ㄋㄧˇ" } },
  { char: "他", zhuyin: { symbol: "ㄊㄚ" } },
  { char: "她", zhuyin: { symbol: "ㄊㄚ" } },
  { char: "它", zhuyin: { symbol: "ㄊㄚ" } },
  { char: "們", zhuyin: { symbol: "ㄇㄣ˙" } },
];

const basicNumberSet = [
  { char: "零", zhuyin: { symbol: "ㄌㄧㄥˊ" } },
  { char: "一", zhuyin: { symbol: "ㄧ" } },
  { char: "二", zhuyin: { symbol: "ㄦˋ" } },
  { char: "三", zhuyin: { symbol: "ㄙㄢ" } },
  { char: "四", zhuyin: { symbol: "ㄙˋ" } },
  { char: "五", zhuyin: { symbol: "ㄨˇ" } },
  { char: "六", zhuyin: { symbol: "ㄌㄧㄡˋ" } },
  { char: "七", zhuyin: { symbol: "ㄑㄧ" } },
  { char: "八", zhuyin: { symbol: "ㄅㄚ" } },
  { char: "九", zhuyin: { symbol: "ㄐㄧㄡˇ" } },
  { char: "十", zhuyin: { symbol: "ㄕˊ" } },
  { char: "幾", zhuyin: { symbol: "ㄐㄧˇ" } },
  { char: "多", zhuyin: { symbol: "ㄉㄨㄛ" } },
  { char: "少", zhuyin: { symbol: "ㄕㄠˇ" } },
];

const basicVerbSet = [
  { char: "是", zhuyin: { symbol: "ㄕˋ" } },
  { char: "想", zhuyin: { symbol: "ㄒㄧㄤˇ" } },
  { char: "要", zhuyin: { symbol: "ㄧㄠˋ" } },
  { char: "吃", zhuyin: { symbol: "ㄔ" } },
  { char: "喝", zhuyin: { symbol: "ㄏㄜ" } },
  { char: "有", zhuyin: { symbol: "ㄧㄡˇ" } },
  { char: "不", zhuyin: { symbol: "ㄅㄨˋ" } },
  { char: "沒", zhuyin: { symbol: "ㄇㄟˊ" } },
  { char: "可", zhuyin: { symbol: "ㄎㄜˇ" } },
  { char: "以", zhuyin: { symbol: "ㄧˇ" } },
  { char: "在", zhuyin: { symbol: "ㄗㄞˋ" } },
  { char: "謝", zhuyin: { symbol: "ㄒㄧㄝˋ" } },
  { char: "說", zhuyin: { symbol: "ㄕㄨㄛ" } },
  { char: "學", zhuyin: { symbol: "ㄒㄩㄝˊ" } },
  { char: "喜", zhuyin: { symbol: "ㄒㄧˇ" } },
  { char: "歡", zhuyin: { symbol: "ㄏㄨㄢ" } },
  { char: "和", zhuyin: { symbol: "ㄏㄜˊ" } },
];

const basicPeopleSet = [
  { char: "人", zhuyin: { symbol: "ㄖㄣˊ" } },
  { char: "朋", zhuyin: { symbol: "ㄆㄥˊ" } },
  { char: "友", zhuyin: { symbol: "ㄧㄡˇ" } },
  { char: "爸", zhuyin: { symbol: "ㄅㄚˋ" } },
  { char: "媽", zhuyin: { symbol: "ㄇㄚ" } },
  { char: "哥", zhuyin: { symbol: "ㄍㄜ" } },
  { char: "姐", zhuyin: { symbol: "ㄐㄧㄝˇ" } },
  { char: "弟", zhuyin: { symbol: "ㄉㄧˋ" } },
  { char: "妹", zhuyin: { symbol: "ㄇㄟˋ" } },
  { char: "家", zhuyin: { symbol: "ㄐㄧㄚ" } },
  { char: "老", zhuyin: { symbol: "ㄌㄠˇ" } },
  { char: "師", zhuyin: { symbol: "ㄕ" } },
];

const basicNounSet = [
  { char: "水", zhuyin: { symbol: "ㄕㄨㄟˇ" } },
  { char: "口", zhuyin: { symbol: "ㄎㄡˇ" } },
  { char: "書", zhuyin: { symbol: "ㄕㄨ" } },
  { char: "車", zhuyin: { symbol: "ㄔㄜ" } },
  { char: "茶", zhuyin: { symbol: "ㄔㄚˊ" } },
  { char: "牛", zhuyin: { symbol: "ㄋㄧㄡˊ" } },
  { char: "豬", zhuyin: { symbol: "ㄓㄨ" } },
  { char: "雞", zhuyin: { symbol: "ㄐㄧ" } },
  { char: "肉", zhuyin: { symbol: "ㄖㄡˋ" } },
  { char: "米", zhuyin: { symbol: "ㄇㄧˇ" } },
  { char: "飯", zhuyin: { symbol: "ㄈㄢˋ" } },
  { char: "菜", zhuyin: { symbol: "ㄘㄞˋ" } },
  { char: "麵", zhuyin: { symbol: "ㄇㄧㄢˋ" } },
];

const basicColorSet = [
  { char: "色", zhuyin: { symbol: "ㄙㄜˋ" } },
  { char: "紅", zhuyin: { symbol: "ㄏㄨㄥˊ" } },
  { char: "藍", zhuyin: { symbol: "ㄌㄢˊ" } },
  { char: "黃", zhuyin: { symbol: "ㄏㄨㄤˊ" } },
  { char: "綠", zhuyin: { symbol: "ㄌㄩˋ" } },
  { char: "黑", zhuyin: { symbol: "ㄏㄟ" } },
  { char: "白", zhuyin: { symbol: "ㄅㄞˊ" } },
];

const basicMiscSet = [
  { char: "個", zhuyin: { symbol: "ㄍㄜ˙" } },
  { char: "太", zhuyin: { symbol: "ㄊㄞˋ" } },
  { char: "很", zhuyin: { symbol: "ㄏㄣˇ" } },
  { char: "好", zhuyin: { symbol: "ㄏㄠˇ" } },
  { char: "什", zhuyin: { symbol: "ㄕㄣˊ" } },
  { char: "麼", zhuyin: { symbol: "ㄇㄜ˙" } },
  { char: "錯", zhuyin: { symbol: "ㄘㄨㄛˋ" } },
  { char: "嗎", zhuyin: { symbol: "ㄇㄚ˙" } },
  { char: "這", zhuyin: { symbol: "ㄓㄜˋ" } },
  { char: "那", zhuyin: { symbol: "ㄋㄚˋ" } },
  { char: "的", zhuyin: { symbol: "ㄉㄜ˙" } },
  { char: "了", zhuyin: { symbol: "ㄌㄜ˙" } },
  { char: "上", zhuyin: { symbol: "ㄕㄤˋ" } },
  { char: "下", zhuyin: { symbol: "ㄒㄧㄚˋ" } },
  { char: "生", zhuyin: { symbol: "ㄕㄥ" } },
];

const beginnerSchoolAddOn = [
  { char: "學", zhuyin: { symbol: "ㄒㄩㄝˊ" } },
  { char: "校", zhuyin: { symbol: "ㄒㄧㄠˋ" } },
  { char: "生", zhuyin: { symbol: "ㄕㄥ" } },
  { char: "書", zhuyin: { symbol: "ㄕㄨ" } },
  { char: "課", zhuyin: { symbol: "ㄎㄜˋ" } },
  { char: "桌", zhuyin: { symbol: "ㄓㄨㄛ" } },
  { char: "筆", zhuyin: { symbol: "ㄅㄧˇ" } },
  { char: "包", zhuyin: { symbol: "ㄅㄠ" } },
  { char: "寫", zhuyin: { symbol: "ㄒㄧㄝˇ" } },
  { char: "讀", zhuyin: { symbol: "ㄉㄨˊ" } },
  { char: "考", zhuyin: { symbol: "ㄎㄠˇ" } },
  { char: "試", zhuyin: { symbol: "ㄕˋ" } },
  { char: "孩", zhuyin: { symbol: "ㄏㄞˊ" } },
  { char: "子", zhuyin: { symbol: "ㄗ˙" } },
  { char: "男", zhuyin: { symbol: "ㄋㄢˊ" } },
  { char: "女", zhuyin: { symbol: "ㄋㄩˇ" } },
];

const beginnerTimeAddOn = [
  { char: "日", zhuyin: { symbol: "ㄖˋ" } },
  { char: "月", zhuyin: { symbol: "ㄩㄝˋ" } },
  { char: "年", zhuyin: { symbol: "ㄋㄧㄢˊ" } },
  { char: "天", zhuyin: { symbol: "ㄊㄧㄢ" } },
  { char: "早", zhuyin: { symbol: "ㄗㄠˇ" } },
  { char: "晚", zhuyin: { symbol: "ㄨㄢˇ" } },
  { char: "時", zhuyin: { symbol: "ㄕˊ" } },
  { char: "分", zhuyin: { symbol: "ㄈㄣ" } },
  { char: "鐘", zhuyin: { symbol: "ㄓㄨㄥ" } },
  { char: "今", zhuyin: { symbol: "ㄐㄧㄣ" } },
  { char: "明", zhuyin: { symbol: "ㄇㄧㄥˊ" } },
  { char: "昨", zhuyin: { symbol: "ㄗㄨㄛˊ" } },
];

const beginnerActionAddOn = [
  { char: "走", zhuyin: { symbol: "ㄗㄡˇ" } },
  { char: "跑", zhuyin: { symbol: "ㄆㄠˇ" } },
  { char: "來", zhuyin: { symbol: "ㄌㄞˊ" } },
  { char: "去", zhuyin: { symbol: "ㄑㄩˋ" } },
  { char: "看", zhuyin: { symbol: "ㄎㄢˋ" } },
  { char: "聽", zhuyin: { symbol: "ㄊㄧㄥ" } },
  { char: "說", zhuyin: { symbol: "ㄕㄨㄛ" } },
  { char: "寫", zhuyin: { symbol: "ㄒㄧㄝˇ" } },
  { char: "讀", zhuyin: { symbol: "ㄉㄨˊ" } },
  { char: "做", zhuyin: { symbol: "ㄗㄨㄛˋ" } },
  { char: "開", zhuyin: { symbol: "ㄎㄞ" } },
  { char: "關", zhuyin: { symbol: "ㄍㄨㄢ" } },
  { char: "坐", zhuyin: { symbol: "ㄗㄨㄛˋ" } },
  { char: "起", zhuyin: { symbol: "ㄑㄧˇ" } },
  { char: "跳", zhuyin: { symbol: "ㄊㄧㄠˋ" } },
  { char: "玩", zhuyin: { symbol: "ㄨㄢˊ" } },
  { char: "愛", zhuyin: { symbol: "ㄞˋ" } },
  { char: "到", zhuyin: { symbol: "ㄉㄠˋ" } },
  { char: "跟", zhuyin: { symbol: "ㄍㄣ" } },
];

const beginnerNatureAddOn = [
  { char: "天", zhuyin: { symbol: "ㄊㄧㄢ" } },
  { char: "地", zhuyin: { symbol: "ㄉㄧˋ" } },
  { char: "山", zhuyin: { symbol: "ㄕㄢ" } },
  { char: "火", zhuyin: { symbol: "ㄏㄨㄛˇ" } },
  { char: "風", zhuyin: { symbol: "ㄈㄥ" } },
  { char: "雨", zhuyin: { symbol: "ㄩˇ" } },
  { char: "雲", zhuyin: { symbol: "ㄩㄣˊ" } },
  { char: "花", zhuyin: { symbol: "ㄏㄨㄚ" } },
  { char: "草", zhuyin: { symbol: "ㄘㄠˇ" } },
  { char: "木", zhuyin: { symbol: "ㄇㄨˋ" } },
  { char: "石", zhuyin: { symbol: "ㄕˊ" } },
  { char: "頭", zhuyin: { symbol: "ㄊㄡˊ" } },
  { char: "氣", zhuyin: { symbol: "ㄑㄧˋ" } },
];

const beginnerPlaceAddOn = [
  { char: "學", zhuyin: { symbol: "ㄒㄩㄝˊ" } },
  { char: "校", zhuyin: { symbol: "ㄒㄧㄠˋ" } },
  { char: "公", zhuyin: { symbol: "ㄍㄨㄥ" } },
  { char: "園", zhuyin: { symbol: "ㄩㄢˊ" } },
  { char: "商", zhuyin: { symbol: "ㄕㄤ" } },
  { char: "店", zhuyin: { symbol: "ㄉㄧㄢˋ" } },
  { char: "醫", zhuyin: { symbol: "ㄧ" } },
  { char: "院", zhuyin: { symbol: "ㄩㄢˋ" } },
  { char: "車", zhuyin: { symbol: "ㄔㄜ" } },
  { char: "站", zhuyin: { symbol: "ㄓㄢˋ" } },
  { char: "圖", zhuyin: { symbol: "ㄊㄨˊ" } },
  { char: "書", zhuyin: { symbol: "ㄕㄨ" } },
  { char: "館", zhuyin: { symbol: "ㄍㄨㄢˇ" } },
  { char: "公", zhuyin: { symbol: "ㄍㄨㄥ" } },
  { char: "司", zhuyin: { symbol: "ㄙ" } },
  { char: "市", zhuyin: { symbol: "ㄕˋ" } },
  { char: "場", zhuyin: { symbol: "ㄔㄤˇ" } },
  { char: "飯", zhuyin: { symbol: "ㄈㄢˋ" } },
  { char: "店", zhuyin: { symbol: "ㄉㄧㄢˋ" } },
  { char: "外", zhuyin: { symbol: "ㄨㄞˋ" } },
  { char: "裡", zhuyin: { symbol: "ㄌㄧˇ" } },
  { char: "面", zhuyin: { symbol: "ㄇㄧㄢˋ" } },
  { char: "哪", zhuyin: { symbol: "ㄋㄚˇ" } },
  { char: "台", zhuyin: { symbol: "ㄊㄞˊ" } },
  { char: "灣", zhuyin: { symbol: "ㄨㄢ" } },
  { char: "美", zhuyin: { symbol: "ㄇㄟˇ" } },
  { char: "國", zhuyin: { symbol: "ㄍㄨㄛˊ" } },
];

const beginnerAnimalAddOn = [
  { char: "狗", zhuyin: { symbol: "ㄍㄡˇ" } },
  { char: "貓", zhuyin: { symbol: "ㄇㄠ" } },
  { char: "鳥", zhuyin: { symbol: "ㄋㄧㄠˇ" } },
  { char: "魚", zhuyin: { symbol: "ㄩˊ" } },
  { char: "馬", zhuyin: { symbol: "ㄇㄚˇ" } },
  { char: "羊", zhuyin: { symbol: "ㄧㄤˊ" } },
];

const beginnerColorAddOn = [
  { char: "紫", zhuyin: { symbol: "ㄗˇ" } },
  { char: "粉", zhuyin: { symbol: "ㄈㄣˇ" } },
];

const beginnerFoodAddOn = [
  { char: "蛋", zhuyin: { symbol: "ㄉㄢˋ" } },
  { char: "豆", zhuyin: { symbol: "ㄉㄡˋ" } },
  { char: "奶", zhuyin: { symbol: "ㄋㄞˇ" } },
  { char: "果", zhuyin: { symbol: "ㄍㄨㄛˇ" } },
  { char: "蘋", zhuyin: { symbol: "ㄆㄧㄥˊ" } },
  { char: "芒", zhuyin: { symbol: "ㄇㄤˊ" } },
  { char: "草", zhuyin: { symbol: "ㄘㄠˇ" } },
  { char: "莓", zhuyin: { symbol: "ㄇㄟˊ" } },
  { char: "包", zhuyin: { symbol: "ㄅㄠ" } },
  { char: "餃", zhuyin: { symbol: "ㄐㄧㄠˇ" } },
];

const intermediateCharAddOn = [
  { char: "對", zhuyin: { symbol: "ㄉㄨㄟˋ" } },
  { char: "過", zhuyin: { symbol: "ㄍㄨㄛˋ" } },
  { char: "難", zhuyin: { symbol: "ㄋㄢˊ" } },
  { char: "變", zhuyin: { symbol: "ㄅㄧㄢˋ" } },
  { char: "畫", zhuyin: { symbol: "ㄏㄨㄚˋ" } },
  { char: "轉", zhuyin: { symbol: "ㄓㄨㄢˇ" } },
  { char: "續", zhuyin: { symbol: "ㄒㄩˋ" } },
  { char: "運", zhuyin: { symbol: "ㄩㄣˋ" } },
  { char: "銀", zhuyin: { symbol: "ㄧㄣˊ" } },
  { char: "飲", zhuyin: { symbol: "ㄧㄣˇ" } },
  { char: "難", zhuyin: { symbol: "ㄋㄢˊ" } },
  { char: "關", zhuyin: { symbol: "ㄍㄨㄢ" } },
  { char: "機", zhuyin: { symbol: "ㄐㄧ" } },
  { char: "圖", zhuyin: { symbol: "ㄊㄨˊ" } },
  { char: "館", zhuyin: { symbol: "ㄍㄨㄢˇ" } },
  { char: "隊", zhuyin: { symbol: "ㄉㄨㄟˋ" } },
  { char: "請", zhuyin: { symbol: "ㄑㄧㄥˇ" } },
  { char: "待", zhuyin: { symbol: "ㄉㄞˋ" } },
  { char: "改", zhuyin: { symbol: "ㄍㄞˇ" } },
  { char: "整", zhuyin: { symbol: "ㄓㄥˇ" } },
  { char: "決", zhuyin: { symbol: "ㄐㄩㄝˊ" } },
  { char: "話", zhuyin: { symbol: "ㄏㄨㄚˋ" } },
  { char: "題", zhuyin: { symbol: "ㄊㄧˊ" } },
  { char: "解", zhuyin: { symbol: "ㄐㄧㄝˇ" } },
  { char: "問", zhuyin: { symbol: "ㄨㄣˋ" } },
  { char: "答", zhuyin: { symbol: "ㄉㄚˊ" } },
  { char: "辦", zhuyin: { symbol: "ㄅㄢˋ" } },
  { char: "法", zhuyin: { symbol: "ㄈㄚˇ" } },
  { char: "權", zhuyin: { symbol: "ㄑㄩㄢˊ" } },
  { char: "利", zhuyin: { symbol: "ㄌㄧˋ" } },
  { char: "據", zhuyin: { symbol: "ㄐㄩˋ" } },
  { char: "報", zhuyin: { symbol: "ㄅㄠˋ" } },
  { char: "導", zhuyin: { symbol: "ㄉㄠˇ" } },
  { char: "演", zhuyin: { symbol: "ㄧㄢˇ" } },
  { char: "響", zhuyin: { symbol: "ㄒㄧㄤˇ" } },
  { char: "像", zhuyin: { symbol: "ㄒㄧㄤˋ" } },
  { char: "環", zhuyin: { symbol: "ㄏㄨㄢˊ" } },
  { char: "境", zhuyin: { symbol: "ㄐㄧㄥˋ" } },
  { char: "資", zhuyin: { symbol: "ㄗ" } },
  { char: "源", zhuyin: { symbol: "ㄩㄢˊ" } },
  { char: "需", zhuyin: { symbol: "ㄒㄩ" } },
  { char: "究", zhuyin: { symbol: "ㄐㄧㄡ" } },
  { char: "竟", zhuyin: { symbol: "ㄐㄧㄥˋ" } },
  { char: "致", zhuyin: { symbol: "ㄓˋ" } },
  { char: "節", zhuyin: { symbol: "ㄐㄧㄝˊ" } },
  { char: "稱", zhuyin: { symbol: "ㄔㄥ" } },
  { char: "該", zhuyin: { symbol: "ㄍㄞ¯" } },
  { char: "勢", zhuyin: { symbol: "ㄕˋ" } },
  { char: "伴", zhuyin: { symbol: "ㄅㄢˋ" } },
  { char: "系", zhuyin: { symbol: "ㄒㄧˋ" } },
  { char: "劇", zhuyin: { symbol: "ㄐㄩˋ" } },
  { char: "段", zhuyin: { symbol: "ㄉㄨㄢˋ" } },
  { char: "快", zhuyin: { symbol: "ㄎㄨㄞˋ" } },
  { char: "慢", zhuyin: { symbol: "ㄇㄢˋ" } },
  { char: "優", zhuyin: { symbol: "ㄧㄡ" } },
  { char: "秀", zhuyin: { symbol: "ㄒㄧㄡˋ" } },
  { char: "選", zhuyin: { symbol: "ㄒㄩㄢˇ" } },
  { char: "擇", zhuyin: { symbol: "ㄗㄜˊ" } },
  { char: "擔", zhuyin: { symbol: "ㄉㄢ" } },
  { char: "負", zhuyin: { symbol: "ㄈㄨˋ" } },
  { char: "責", zhuyin: { symbol: "ㄗㄜˊ" } },
  { char: "察", zhuyin: { symbol: "ㄔㄚˊ" } },
  { char: "典", zhuyin: { symbol: "ㄉㄧㄢˇ" } },
  { char: "準", zhuyin: { symbol: "ㄓㄨㄣˇ" } },
  { char: "備", zhuyin: { symbol: "ㄅㄟˋ" } },
  { char: "料", zhuyin: { symbol: "ㄌㄧㄠˋ" } },
  { char: "慎", zhuyin: { symbol: "ㄕㄣˋ" } },
  { char: "薦", zhuyin: { symbol: "ㄐㄧㄢˋ" } },
  { char: "激", zhuyin: { symbol: "ㄐㄧ" } },
  { char: "載", zhuyin: { symbol: "ㄗㄞˋ" } },
  { char: "跨", zhuyin: { symbol: "ㄎㄨㄚˋ" } },
  { char: "孫", zhuyin: { symbol: "ㄙㄨㄣ" } },
  { char: "胞", zhuyin: { symbol: "ㄅㄠ" } },
  { char: "廷", zhuyin: { symbol: "ㄊㄧㄥ" } },
  { char: "倒", zhuyin: { symbol: "ㄉㄠˇ" } },
  { char: "歧", zhuyin: { symbol: "ㄑㄧˊ" } },
  { char: "視", zhuyin: { symbol: "ㄕˋ" } },
  { char: "打", zhuyin: { symbol: "ㄉㄚˇ" } },
  { char: "敗", zhuyin: { symbol: "ㄅㄞ" } },
  { char: "迫", zhuyin: { symbol: "ㄆㄛˋ" } },
  { char: "賞", zhuyin: { symbol: "ㄕㄤˇ" } },
  { char: "狀", zhuyin: { symbol: "ㄓㄨㄤˋ" } },
  { char: "慮", zhuyin: { symbol: "ㄌㄩˋ" } },
  { char: "橋", zhuyin: { symbol: "ㄑㄧㄠˊ" } },
  { char: "幅", zhuyin: { symbol: "ㄈㄨˊ" } },
  { char: "篇", zhuyin: { symbol: "ㄆㄧㄢ" } },
  { char: "冒", zhuyin: { symbol: "ㄇㄠˋ" } },
  { char: "露", zhuyin: { symbol: "ㄌㄨˋ" } },
  { char: "兔", zhuyin: { symbol: "ㄊㄨˋ" } },
  { char: "熊", zhuyin: { symbol: "ㄒㄩㄥˊ" } },
  { char: "糖", zhuyin: { symbol: "ㄊㄤˊ" } },
  { char: "油", zhuyin: { symbol: "ㄧㄡˊ" } },
  { char: "鹽", zhuyin: { symbol: "ㄧㄢˊ" } },
  { char: "臺", zhuyin: { symbol: "ㄊㄞˊ" } },
];

const intermediateArticleAddOn = [
  { char: "呢", zhuyin: { symbol: "ㄋㄜ˙" } },
  { char: "吧", zhuyin: { symbol: "ㄅㄚ˙" } },
  { char: "啊", zhuyin: { symbol: "ㄚ˙" } },
  { char: "哦", zhuyin: { symbol: "ㄛˋ" } },
];

const advancedCharAddOn = [
  { char: "懼", zhuyin: { symbol: "ㄐㄩˋ" } },
  { char: "縱", zhuyin: { symbol: "ㄗㄨㄥˋ" } },
  { char: "翻", zhuyin: { symbol: "ㄈㄢ" } },
  { char: "譯", zhuyin: { symbol: "ㄧˋ" } },
  { char: "憂", zhuyin: { symbol: "ㄧㄡ" } },
  { char: "顯", zhuyin: { symbol: "ㄒㄧㄢˇ" } },
  { char: "析", zhuyin: { symbol: "ㄒㄧ" } },
  { char: "媒", zhuyin: { symbol: "ㄇㄟˊ" } },
  { char: "體", zhuyin: { symbol: "ㄊㄧˇ" } },
  { char: "載", zhuyin: { symbol: "ㄗㄞˋ" } },
  { char: "層", zhuyin: { symbol: "ㄘㄥˊ" } },
  { char: "拓", zhuyin: { symbol: "ㄊㄨㄛˋ" } },
  { char: "增", zhuyin: { symbol: "ㄗㄥ" } },
  { char: "加", zhuyin: { symbol: "ㄐㄧㄚ" } },
  { char: "減", zhuyin: { symbol: "ㄐㄧㄢˇ" } },
  { char: "薦", zhuyin: { symbol: "ㄐㄧㄢˋ" } },
  { char: "韻", zhuyin: { symbol: "ㄩㄣˋ" } },
  { char: "錄", zhuyin: { symbol: "ㄌㄨˋ" } },
  { char: "慶", zhuyin: { symbol: "ㄑㄧㄥˋ" } },
  { char: "療", zhuyin: { symbol: "ㄌㄧㄠˊ" } },
  { char: "慣", zhuyin: { symbol: "ㄍㄨㄢˋ" } },
  { char: "徹", zhuyin: { symbol: "ㄔㄜˋ" } },
  { char: "臨", zhuyin: { symbol: "ㄌㄧㄣˊ" } },
  { char: "縫", zhuyin: { symbol: "ㄈㄥˊ" } },
  { char: "悍", zhuyin: { symbol: "ㄏㄢˋ" } },
  { char: "擾", zhuyin: { symbol: "ㄖㄠˇ" } },
  { char: "募", zhuyin: { symbol: "ㄇㄨˋ" } },
  { char: "冶", zhuyin: { symbol: "ㄧㄝˇ" } },
  { char: "惹", zhuyin: { symbol: "ㄖㄜˇ" } },
  { char: "漠", zhuyin: { symbol: "ㄇㄛˋ" } },
  { char: "駐", zhuyin: { symbol: "ㄓㄨˋ" } },
  { char: "斂", zhuyin: { symbol: "ㄌㄧㄢˇ" } },
  { char: "躍", zhuyin: { symbol: "ㄩㄝˋ" } },
  { char: "覆", zhuyin: { symbol: "ㄈㄨˋ" } },
  { char: "頹", zhuyin: { symbol: "ㄊㄨㄟˊ" } },
  { char: "惕", zhuyin: { symbol: "ㄊㄧˋ" } },
  { char: "鎖", zhuyin: { symbol: "ㄙㄨㄛˇ" } },
  { char: "裂", zhuyin: { symbol: "ㄌㄧㄝˋ" } },
  { char: "澄", zhuyin: { symbol: "ㄔㄥˊ" } },
  { char: "弧", zhuyin: { symbol: "ㄏㄨˊ" } },
  { char: "倘", zhuyin: { symbol: "ㄊㄤˇ" } },
  { char: "戲", zhuyin: { symbol: "ㄒㄧˋ" } },
  { char: "碑", zhuyin: { symbol: "ㄅㄟ" } },
  { char: "慈", zhuyin: { symbol: "ㄘˊ" } },
  { char: "邁", zhuyin: { symbol: "ㄇㄞˋ" } },
  { char: "烙", zhuyin: { symbol: "ㄌㄠˋ" } },
  { char: "墮", zhuyin: { symbol: "ㄉㄨㄛˋ" } },
  { char: "劫", zhuyin: { symbol: "ㄐㄧㄝˊ" } },
  { char: "搏", zhuyin: { symbol: "ㄅㄛˊ" } },
  { char: "挫", zhuyin: { symbol: "ㄘㄨㄛˋ" } },
  { char: "誓", zhuyin: { symbol: "ㄕˋ" } },
  { char: "憤", zhuyin: { symbol: "ㄈㄣˋ" } },
  { char: "盟", zhuyin: { symbol: "ㄇㄥˊ" } },
  { char: "懲", zhuyin: { symbol: "ㄔㄥˊ" } },
  { char: "脆", zhuyin: { symbol: "ㄘㄨㄟˋ" } },
  { char: "鞏", zhuyin: { symbol: "ㄍㄨㄥˇ" } },
  { char: "襲", zhuyin: { symbol: "ㄒㄧˊ" } },
  { char: "廉", zhuyin: { symbol: "ㄌㄧㄢˊ" } },
  { char: "緩", zhuyin: { symbol: "ㄏㄨㄢˇ" } },
  { char: "斑", zhuyin: { symbol: "ㄅㄢ" } },
  { char: "祿", zhuyin: { symbol: "ㄌㄨˋ" } },
  { char: "闊", zhuyin: { symbol: "ㄎㄨㄛˋ" } },
  { char: "竄", zhuyin: { symbol: "ㄘㄨㄢˋ" } },
  { char: "顫", zhuyin: { symbol: "ㄓㄢˋ" } },
  { char: "殲", zhuyin: { symbol: "ㄐㄧㄢ" } },
  { char: "焉", zhuyin: { symbol: "ㄧㄢ" } },
  { char: "珊", zhuyin: { symbol: "ㄕㄢ" } },
  { char: "峽", zhuyin: { symbol: "ㄒㄧㄚˊ" } },
  { char: "腥", zhuyin: { symbol: "ㄒㄧㄥ" } },
  { char: "妓", zhuyin: { symbol: "ㄐㄧˋ" } },
  { char: "憑", zhuyin: { symbol: "ㄆㄧㄥˊ" } },
  { char: "膠", zhuyin: { symbol: "ㄐㄧㄠ" } },
  { char: "窮", zhuyin: { symbol: "ㄑㄩㄥˊ" } },
  { char: "紮", zhuyin: { symbol: "ㄓㄚ" } },
  { char: "謀", zhuyin: { symbol: "ㄇㄡˊ" } },
  { char: "鏡", zhuyin: { symbol: "ㄐㄧㄥˋ" } },
  { char: "慕", zhuyin: { symbol: "ㄇㄨ" } },
  { char: "賦", zhuyin: { symbol: "ㄈㄨˋ" } },
  { char: "堵", zhuyin: { symbol: "ㄉㄨˇ" } },
  { char: "掘", zhuyin: { symbol: "ㄐㄩㄝˊ" } },
  { char: "險", zhuyin: { symbol: "ㄒㄧㄢˇ" } },
  { char: "恍", zhuyin: { symbol: "ㄏㄨㄤˇ" } },
  { char: "咆", zhuyin: { symbol: "ㄆㄠˊ" } },
  { char: "瑰", zhuyin: { symbol: "ㄍㄨㄟ" } },
  { char: "醞", zhuyin: { symbol: "ㄩㄣˋ" } },
  { char: "鬥", zhuyin: { symbol: "ㄉㄡˋ" } },
  { char: "鬧", zhuyin: { symbol: "ㄋㄠˋ" } },
];

const advancedArticleAddOn = [
  { char: "喔", zhuyin: { symbol: "ㄛ˙" } },
  { char: "唄", zhuyin: { symbol: "ㄅㄟ˙" } },
  { char: "诶", zhuyin: { symbol: "ㄟ" } },
  { char: "啦", zhuyin: { symbol: "ㄌㄚ˙" } },
  { char: "喽", zhuyin: { symbol: "ㄌㄡ˙" } },
];

// COMPOSITE SETS

export const newbieSet = [
  ...basicPronounSet,
  ...basicNumberSet,
  ...basicVerbSet,
  ...basicPeopleSet,
  ...basicNounSet,
  ...basicColorSet,
  ...basicMiscSet,
];

export const beginnerAddOnSet = [
  ...beginnerSchoolAddOn,
  ...beginnerTimeAddOn,
  ...beginnerActionAddOn,
  ...beginnerNatureAddOn,
  ...beginnerPlaceAddOn,
  ...beginnerAnimalAddOn,
  ...beginnerColorAddOn,
  ...beginnerFoodAddOn,
];

export const intermediateAddOnSet = [
  ...intermediateCharAddOn,
  ...intermediateArticleAddOn,
];

export const advancedAddOnSet = [
  ...advancedCharAddOn,
  ...advancedArticleAddOn,
];
